### ISSUE TITLE
Title field in wide modal window does not always expand

### ISSUE THREAD

**Issue by pillrin** [VoteIT/voteit.core#269]
Look at image. It does not expand. If i close the window and open it again i usually expands all the way.

![Ska rmavbild 2013-02-28 kl 11 13 40](https://f.cloud.github.com/assets/765306/206066/07a390f6-81c2-11e2-98f6-63d193e30e04.png)

**Comment by robinharms** [comment]
Cute :)
It's not an issue in twitter bootstrap so it will go away in the new release
