### ISSUE TITLE
JS scroll problem may cause autoscroll to top?

### ISSUE THREAD

**Issue by pillrin** [VoteIT/voteit.core#293]
As mentioned on VoteIT Facebook page by Melin:

Er sida buggar, jag tillåts inte scrolla hela vägen ner för att se kontaktuppgifter, länk till engelska eller liknande - frustrerande

(händer när man får ett felmeddelande, som att man måste vara inloggad)

Felet uppstod här: http://riksmote.voteit.se/riksmote2013 - jag tvingas tillbaka till att varningsrutan är i toppen på skärmen hela tiden - så troligen ett javascript som behöver lösas.

**Comment by robinharms** [comment]
New version doesn't have this
