### ISSUE TITLE
Multiple login modals

### ISSUE THREAD

**Issue by scriptcoded** [VoteIT/voteit.core#351]
Clicking the login button multiple times before the modal opens results in multiple modals opening, som containing multiple bodies.

Steps to reproduce:
- Click the login button multiple times before the login modal opens.

**Comment by robinharms** [comment]
Hi, I've never managed to do that. It took some work to reproduce :)
I'll add something that blocks multiple requests.

Thanks for the bug report!

**Comment by robinharms** [comment]
It was a problem in another framework, but it's fixed there and will be pushed out shortly. Thanks a lot!
