### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by 01ste02** [VoteIT/voteit.core#369]
Python 2,7 has been EOL since 2020. Is there a plan to update voteit for python3?

**Comment by robinharms** [comment]
Nope, we've rewritten the whole codebase from scratch and will release a new version soon. It's being tested right now. We haven't published the source yet but it will be open as well soon. (Published here)

**Comment by robinharms** [comment]
Not really, the whole project is maintained through the membership fees.

Deploying VoteIT 4 yourself won't be possible for at least another year i think. (If ever, considering the amount of docs it would require us to produce) And for that scale it would be more expensive to pay for servers than simply joining the organisation.

**Comment by 01ste02** [comment]
We are a student organization and love to tinker with our servers in our spare time, and we should be able to run it on our own server cluster. Since we are composed of students from the Computer Science program, there might be more than a few people that would be interested in contributing to voteIT if we deploy it and they get to see it in action.  

It is understandable that you cannot produce documentation for the general public to be able to run it, but we would still like to try even without documentation. It is more interesting for us to self-host than to run paid softwares that we do not manage ourselves. We already have offers to run other voting-programs for free, but want voteIT because of the flexibility and self-hosting. Do you recommend that we go with another offer rather than wait for the python3 code to be published?

**Comment by robinharms** [comment]
Not sure, but it's something you might want to checkout yourselves :)
Which organisation is it?

I can give you read access in advance of the release so you can determine yourself if this is something you want to run.

**Comment by 01ste02** [comment]
It is "D-sektionen inom TLTH" that I am sys-admin for. We'd love to get read-access and try for ourselves. How would we go about getting that?

**Comment by robinharms** [comment]
Sorry for the late reply, drop me a line at robin@betahaus.net and i'll set it up!
